<!-- ## Shiny App Structure -->

<!-- For sharing purposes, standardisation of formats is required.  -->

<!-- A shiny app app can either be: -->

<!--   - fully contained in a `app.R` file -->
<!--   - divided into `server.R`, `ui.R` and  `global.R `. -->

<!-- All these files should be placed in the same directory. -->

<!-- The metadata for the app should be contained in a folder named `www`. -->

<!-- ## Share a Shiny App -->

<!-- <!-- A Shiny app is mantained by a computer running R. This can be your own laptop or a web server.  --> -->

<!-- <!-- Examples for sharing your app are: --> -->

<!-- <!-- - Shinyapps.io and Shiny Server, powered by Rstudio, allow you to share your apps online --> -->
<!-- <!-- - ShinyProxy permits to deploy Shiny apps in an enterprise context --> -->
<!-- <!-- - On your own server, exploiting docker --> -->

<!-- <!-- Additionally  <font style="color: #008cc3; !important;"> **a shiny app can be shared as part of a package.** </font> --> -->

<!-- <!-- ## Shiny App in a Package --> -->

<!-- A Shiny app is mantained by a computer running R. This can be your own laptop or a web server (.e. Shinyapps.io, Shiny Server, ShinyProxy). -->

<!-- Additionally **a shiny app can be part of a package.** -->

<!-- <!-- A package is a structured single entity that can be distributed freely to other users.  --> -->

<!-- <div style="color: #008cc3; !important;"> -->
<!-- * Shiny app wrapped in a package, containing only the app: -->
<!-- </div> -->

<!-- <div style="margin-left:100px !important;"> -->
<!-- In such case, the package functionalities are not available outside of the app itself. -->
<!-- </div> -->

<!-- <div style="color: #008cc3; !important;"> -->
<!-- * Package including a shiny app.  -->
<!-- </div> -->

<!-- <div style="margin-left:100px !important;"> -->
<!-- In such case the app, works as interface for the package and the package functionalities can be accessed independently of the app. -->
<!-- </div> -->

<!-- ## SmaRP Structure -->

<!--  **SmaRP** is is implemented as a shiny pension calculator web app, in the form of an R package.  -->

<!-- * The functions belonging to the package are stored under `R` -->
<!-- * Data used in the package is made available under `data` -->
<!-- * The app is stored under `inst` in a typical shiny app folder structure. -->
<!-- * The `tests` folder contains automatised checks for the package. -->
<!-- * Code documentation is available under `man`. -->
<!-- * A user manual is contained in `vignettes`. -->
<!-- * The files `NAMESPACE` & `DESCRIPTION` indicate the package dependencies. -->
<!-- * The `README.md` file provides information about the package -->


## SmaRP Structure Advantages

 **SmaRP** is is implemented as a shiny pension calculator web app, in the form of an R package, which includes a Shiny app. In such case the app, works as interface for the package and the package functionalities can be accessed independently of the app.
 
Advantages:

* The code can be easly <font style="color: #008cc3 !important;">documented</font> via `roxygen` tags
* <font style="color: #008cc3 !important;">Tests</font> can be be included in the package to check each function independently
* A user manual can be provided in form of <font style="color: #008cc3 !important;">vignettes</font> 
* Clear identification of <font style="color: #008cc3 !important;">dependencies</font> via `NAMESPACE` & `DESCRIPTION` (package won't build if requirements are not met)
* Easy documentation of <font style="color: #008cc3 !important;">version</font> changes via `NEWS.md` an release tags

## SmaRP Structure Disadvantages

To be consistent with such a structure, it is important to:

- keep all data manipulations as functions under the `R` folder
- embed all app related functionalities under `ui.R`, `server.R` and `global.R`

However, <div style="color: #008cc3 !important; display: inline-block;"> **keeping things perfect is difficult!** </div>

- there are data manipulations which are needed solely for the app and would naturally belong in the app itself (i.e. data restructuring for plotting)
- might be useful to store some app related constructs as functions if they are used in multiple places (e.g. shiny modules) 

