# test e.g. via
#   docker build --pull -t install_scripts:smarp-test -f docker/Dockerfile-test-scripts .
#   docker run --rm install_scripts:smarp-test bash -c 'pandoc -v'
#   docker run --rm install_scripts:smarp-test R -e 'tinytex::tlmgr_install("beamer")'
#   docker run --rm install_scripts:smarp-test bash /reinstall_tinytex.sh
FROM rocker/r-ver:3.5.3

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ## for install_pandoc.sh and install_tinytex.sh
    wget \
    ## for install_tinytex.sh
    texinfo \
    ## for install_tinytex.sh
    ghostscript \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/

# Pandoc
ENV PANDOC_DEB="2.3.1/pandoc-2.3.1-1-amd64.deb"
COPY docker/install_pandoc.sh .
RUN sh install_pandoc.sh $PANDOC_DEB

# TinyTeX
COPY docker/install_tinytex.sh .
# Use the frozen TeXLive 2018 snapshot as version-stable tlnet CTAN archive
ENV CTAN_REPO=http://www.texlive.info/tlnet-archive/2019/02/27/tlnet
RUN sh install_tinytex.sh fancyhdr

# Re-installation of TinyTeX, to be used inside a running container in case the
# TeXLive local repo becomes obsolete (Remote repository is newer than local),
# in case of non-version-stable TinyTeX installs
COPY docker/reinstall_tinytex.sh .
